version: '3.7'
services:
  server:
    build:
      context: ./gold-server/
    image: gold-server:latest
    working_dir: /app
    volumes:
      - ./gold-server/:/app
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
     - ./db/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306